import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
const SUPABASE_URL=Deno.env.get("SUPABASE_URL")!;
const SERVICE_KEY=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const PUBLISHABLE_KEYS=Deno.env.get("SUPABASE_PUBLISHABLE_KEYS")||"{}";
const CLIENT_ID=Deno.env.get("PAYPAL_CLIENT_ID")!;
const CLIENT_SECRET=Deno.env.get("PAYPAL_CLIENT_SECRET")!;
const WEBHOOK_ID=Deno.env.get("PAYPAL_WEBHOOK_ID")!;
const PAYPAL_BASE=Deno.env.get("PAYPAL_API_BASE")||"https://api-m.paypal.com";
const admin=createClient(SUPABASE_URL,SERVICE_KEY);
const cors={"Content-Type":"application/json","Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type"};
const out=(x,s=200)=>new Response(JSON.stringify(x),{status:s,headers:cors});
async function token(){const r=await fetch(PAYPAL_BASE+"/v1/oauth2/token",{method:"POST",headers:{"Authorization":"Basic "+btoa(CLIENT_ID+":"+CLIENT_SECRET),"Content-Type":"application/x-www-form-urlencoded"},body:"grant_type=client_credentials"});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error("PayPal OAuth "+r.status+": "+(d.error_description||d.error||"authentication failed"));return d.access_token;}
async function pp(path,options={}){const t=await token();const r=await fetch(PAYPAL_BASE+path,{...options,headers:{"Authorization":"Bearer "+t,"Content-Type":"application/json",...(options.headers||{})}});const d=await r.json().catch(()=>({}));return {r,d};}
async function user(req){const a=req.headers.get("Authorization")||"";if(!a.startsWith("Bearer "))return null;const keys=JSON.parse(PUBLISHABLE_KEYS);const key=keys.default||Deno.env.get("SUPABASE_ANON_KEY")||"";if(!key)return null;const c=createClient(SUPABASE_URL,key);const {data}=await c.auth.getUser(a.slice(7));return data.user||null;}
async function createOrder(req){const u=await user(req);if(!u)return out({error:"Authentication required."},401);const {r,d}=await pp("/v2/checkout/orders",{method:"POST",body:JSON.stringify({intent:"CAPTURE",purchase_units:[{custom_id:u.id,description:"QuotePilot Founding Plan",amount:{currency_code:"USD",value:"49.00"}}],application_context:{brand_name:"QuotePilot",user_action:"PAY_NOW",return_url:"https://xaviercampbell3000.github.io/contractor-quotepilot/?payment=success",cancel_url:"https://xaviercampbell3000.github.io/contractor-quotepilot/?payment=cancelled"}})});if(!r.ok)return out({error:d.message||"PayPal order creation failed."},502);const approval=d.links?.find((x)=>x.rel==="approve")?.href;if(!approval)return out({error:"PayPal approval link was not returned."},502);await admin.from("entitlements").upsert({user_id:u.id,plan:"founding",status:"pending",paypal_order_id:d.id,updated_at:new Date().toISOString()},{onConflict:"user_id"});return out({order_id:d.id,approval_url:approval});}
async function captureOrder(req){const u=await user(req);if(!u)return out({error:"Authentication required."},401);const b=await req.json().catch(()=>({}));const id=String(b.order_id||"");if(!id)return out({error:"Missing order_id."},400);const {r:or,d:od}=await pp("/v2/checkout/orders/"+encodeURIComponent(id),{method:"GET"});if(!or.ok)return out({error:"PayPal order could not be verified."},502);const orderUid=od.purchase_units?.[0]?.custom_id;if(orderUid!==u.id)return out({error:"This PayPal order does not belong to this account."},403);const {r,d}=await pp("/v2/checkout/orders/"+encodeURIComponent(id)+"/capture",{method:"POST",body:"{}"});if(!r.ok&&d.name!=="UNPROCESSABLE_ENTITY")return out({error:d.message||"PayPal capture failed."},502);const unit=d.purchase_units?.[0];const cap=unit?.payments?.captures?.[0];const uid=unit?.custom_id;const amount=cap?.amount?.value;const currency=cap?.amount?.currency_code;if(d.status!=="COMPLETED"||amount!=="49.00"||currency!=="USD"||uid!==u.id)return out({error:"Payment was not confirmed for this account."},400);await admin.from("entitlements").upsert({user_id:u.id,plan:"founding",status:"active",paypal_order_id:id,paypal_capture_id:cap.id,paid_at:new Date().toISOString(),updated_at:new Date().toISOString()},{onConflict:"user_id"});return out({status:"active"});}
async function webhook(req){try{await req.text();return out({received:true,diagnostic:"webhook reached"});let event;try{event=JSON.parse(raw);}catch(e){return out({error:"Webhook JSON parse failed.",debug:{message:e?.message||String(e)}},400);}const h=req.headers;const verification={transmission_id:h.get("paypal-transmission-id"),transmission_time:h.get("paypal-transmission-time"),cert_url:h.get("paypal-cert-url"),auth_algo:h.get("paypal-auth-algo"),transmission_sig:h.get("paypal-transmission-sig"),webhook_id:WEBHOOK_ID,webhook_event:event};let t;try{t=await token();}catch(e){return out({error:"PayPal authentication failed.",debug:{message:e?.message||String(e),api_base:PAYPAL_BASE}},400);}let vr;try{vr=await fetch(PAYPAL_BASE+"/v1/notifications/verify-webhook-signature",{method:"POST",headers:{"Authorization":"Bearer "+t,"Content-Type":"application/json"},body:JSON.stringify(verification)});}catch(e){return out({error:"PayPal verification request failed.",debug:{message:e?.message||String(e),api_base:PAYPAL_BASE}},400);}const vd=await vr.json().catch(()=>({}));if(vd.verification_status!=="SUCCESS")return out({error:"Invalid webhook signature.",debug:{http_status:vr.status,verification_status:vd.verification_status||null,paypal_response:vd,api_base:PAYPAL_BASE,webhook_id_present:Boolean(WEBHOOK_ID)}},400);return out({received:true});}catch(e){return out({error:"Webhook unexpected error.",debug:{message:e?.message||String(e)}},400);}}
Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response("ok",{headers:cors});try{const p=new URL(req.url).pathname;if(p.endsWith("/create-order")&&req.method==="POST")return await createOrder(req);if(p.endsWith("/capture-order")&&req.method==="POST")return await captureOrder(req);if(req.method==="POST"&&!(p.endsWith("/create-order")||p.endsWith("/capture-order")))return await webhook(req);return out({error:"Not found."},404);}catch(e){return out({error:e?.message||String(e)},500);}});